// ⚠️ Ne pas modifier ce fichier — Do not edit this file
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import path from 'path'
import { resumeSeoPlugin } from './vite-plugin-resume-seo'
import { assetsDetectPlugin } from './vite-plugin-assets-detect'
import { resumeValidatePlugin } from './vite-plugin-resume-validate'

export default defineConfig({
  // Relative base: works whether the site is served from a domain root
  // (custom domain) or a subpath (https://<user>.github.io/<repo>/),
  // without needing to detect which one applies at build time.
  base: './',
  plugins: [react(), tailwindcss(), assetsDetectPlugin(), resumeValidatePlugin(), resumeSeoPlugin()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
